### ISSUE TITLE
我想设置成"只能在某群使用"

### ISSUE THREAD

**Issue by Xian0Grem** [cubstaryow/nonebot-plugin-authrespond#5]
我先给“”全员“”加了  黑名单
然后给“”特定群“”加了  白名单
我预期是只能在"特定群"使用
但是操作后即使在"特定群"依然无法使用

**Comment by Xian0Grem** [comment]
哦 原来加群白后面跟的是用户id,
但是我如何实现我的预期呢🤔

**Comment by cubstaryow** [comment]
emmmmm，好久没看我已经不知道我写的是什么了（）

**Comment by cubstaryow** [comment]
但是我自己又用着没问题，所以我也没法追踪问题

**Comment by cubstaryow** [comment]
ok搞定了
