### ISSUE TITLE
无效禁令

### ISSUE THREAD

**Issue by NikoCat233** [cubstaryow/nonebot-plugin-authrespond#6]
无法封禁fortune插件
![image](https://github.com/user-attachments/assets/24600801-0a4a-48a0-ac57-9c52d4a42469)

**Comment by cubstaryow** [comment]
你是超级管理员，此插件默认忽略对超级管理员的封禁，可以看后台有无来自插件的 warning 日志确认其是否工作

**Comment by cubstaryow** [comment]
本来超级管理员的定位就是最高权限啊，哪里有说封最高权限的🧐

**Comment by NikoCat233** [comment]
这对理解能力不够的小白不够友好 ;(
